// eslint-disable-next-line import/no-anonymous-default-export
export default {
  name: "Fatemeh Raiyat",
  home: "HOME",
  about: "ABOUT",
  resume: "RESUME",
  portfolios: "PORTFOLIOS",
  contact: "CONTACT",
  hi: "Hi, I am",
  hi2: "",
  desc:
    "Frontend Web Developer with a focus on JavaScript including React and Redux.",
  aboutme: "ABOUT ME",
  services: "SERVICES",
  fullname: "FullName",
  nationality: "Nationality",
  languages: "Languages",
  email: "Email",
  year: "Years",
  irani: "Iran",
  persian: "Persian",
  english: "English",
  german: "German",
  downloadcv: "DOWNLOAD CV",
  myskill: "MY SKILLS",
  workingExperience: " Working Experience",
  educationalQualification: "Educational Qualification",
  workingSteps: [
    {
      id: -1,
      date: "",
      title: "",
      subtitle: "",
      content: "",
    },
    {
      id: 0,
      date: "2018-2020",
      title: "Master of science",
      subtitle: "tehran",
      content:
        "ipsum as it is sometimes known. is dummy text used in laying out print.graphic or web designs.use in a type specimen book.",
    },
    {
      id: 1,
      date: "2018-2020",
      title: "master",
      subtitle: "tehran",
      content:
        "ipsum as it is sometimes known. is dummy text used in laying out print.graphic or web designs.use in a type specimen book.",
    },
    {
      id: -2,
      date: "",
      title: "",
      subtitle: "",
      content: "",
    },
  ],
  educationalSteps: [
    {
      id: -1,
      date: "",
      title: "",
      subtitle: "",
      content: "",
    },
    {
      id: 0,
      date: "2018-2020",
      title: "Master Of Software Engineering",
      subtitle: "Azad University",
      content: "Iran, Tehran",
    },
    {
      id: 1,
      date: "2018-2020",
      title: "Bachelor Of Software Engineering",
      subtitle: "Birjand University",
      content: "Iran, Birjand",
    },
    {
      id: -2,
      date: "",
      title: "",
      subtitle: "",
      content: "",
    },
  ],
  contactme: "CONTACT ME",
  touch: "GET IN TOUCH",
  phone: "Phone",
  address: "Address",
  addressdesc:"Iran, Shiraz",
  nameform: "Enter Your Name...",
  subjectform: "Enter Your Subject...",
  emailform: "Enter Your Email...",
  messageform: "Enter Your Message... ",
  sendbtn:"SEND MESSAGE",
};
